

export const metadata = {
    title: "Next and Sanity",
    description: "Generated by Next.js | Modified by Mohammed Saheed Shittu",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}